/* Build-time helper: turns the supplied SVG lockup into canvas Path2D data the
   reel can animate per part, plus a tiny SVG builder for tinted raster use.
     node tools/logo.mjs                      → src/layers/logo.js
     node tools/logo.mjs some/other.svg out.js
   Scripted (not hand-copied) so the geometry in the animation is literally the
   geometry in the brand file. */
import fs from "node:fs";
import path from "node:path";

const SRC = process.argv[2] || path.resolve(import.meta.dirname, "../src/layers/logo-src.svg");
const OUT = process.argv[3] || path.resolve(import.meta.dirname, "../src/layers/logo.js");

const svg = fs.readFileSync(SRC, "utf8");
const vbm = svg.match(/viewBox="([^"]+)"/);
const vb = vbm ? vbm[1].trim().split(/[\s,]+/).map(Number) : [0, 0, 908, 275];

/* --- minimal absolute/relative path walker, just for bboxes --- */
function bbox(d) {
  const re = /([MmLlHhVvCcSsQqTtAaZz])([^MmLlHhVvCcSsQqTtAaZz]*)/g;
  let x = 0, y = 0, sx = 0, sy = 0, px = 0, py = 0;
  let minx = Infinity, miny = Infinity, maxx = -Infinity, maxy = -Infinity;
  const hit = (a, b) => {
    if (a < minx) minx = a;
    if (a > maxx) maxx = a;
    if (b < miny) miny = b;
    if (b > maxy) maxy = b;
  };
  let m;
  while ((m = re.exec(d))) {
    const c = m[1];
    const n = (m[2].match(/-?\d*\.?\d+(?:e[-+]?\d+)?/gi) || []).map(Number);
    const abs = c === c.toUpperCase();
    const ox = abs ? 0 : x, oy = abs ? 0 : y;
    switch (c.toUpperCase()) {
      case "M":
        for (let i = 0; i + 1 < n.length; i += 2) {
          x = ox + n[i]; y = oy + n[i + 1];
          if (i === 0) { sx = x; sy = y; }
          hit(x, y);
        }
        break;
      case "L":
      case "T":
        for (let i = 0; i + 1 < n.length; i += 2) { x = ox + n[i]; y = oy + n[i + 1]; hit(x, y); }
        break;
      case "H":
        n.forEach((v) => { x = ox + v; hit(x, y); });
        break;
      case "V":
        n.forEach((v) => { y = oy + v; hit(x, y); });
        break;
      case "C":
        for (let i = 0; i + 5 < n.length; i += 6) {
          hit(ox + n[i], oy + n[i + 1]); hit(ox + n[i + 2], oy + n[i + 3]);
          x = ox + n[i + 4]; y = oy + n[i + 5]; hit(x, y);
        }
        break;
      case "S":
      case "Q":
        for (let i = 0; i + 3 < n.length; i += 4) {
          hit(ox + n[i], oy + n[i + 1]);
          x = ox + n[i + 2]; y = oy + n[i + 3]; hit(x, y);
        }
        break;
      case "A":
        for (let i = 0; i + 6 < n.length; i += 7) {
          const rx = n[i], ry = n[i + 1];
          x = ox + n[i + 5]; y = oy + n[i + 6];
          hit(x - rx, y - ry); hit(x + rx, y + ry);
        }
        break;
      case "Z":
        x = sx; y = sy;
        break;
    }
    px = x; py = y;
  }
  return isFinite(minx) ? [minx, miny, maxx - minx, maxy - miny] : [0, 0, 0, 0];
}

const parts = [];
const re = /<path\b[^>]*>/g;
let m;
while ((m = re.exec(svg))) {
  const tag = m[0];
  const d = (tag.match(/\sd="([^"]+)"/) || [])[1];
  if (!d || d.length < 8) continue;
  const fill = (tag.match(/fill="(#[0-9a-fA-F]{3,8})"/) || [])[1] || "#373B42";
  const rule = /fill-rule="evenodd"/.test(tag) ? "evenodd" : "nonzero";
  const bb = bbox(d);
  /* group split tuned to this lockup: emblem on the left, one tagline row at
     the bottom, wordmark in between */
  /* four animation-ready pieces, read straight off the artwork:
     the tree-ring emblem · the furniture vignette inside it · the letters · the tagline */
  if (bb[2] < 1 && bb[3] < 1) continue; /* zero-area artefact in the source file */
  const g =
    bb[1] > vb[1] + vb[3] * 0.66 ? "tag"
    : bb[0] + bb[2] <= vb[2] * 0.39 ? "mark"
    : bb[0] < vb[2] * 0.35 ? "furn"
    : "word";
  parts.push({ d: d.replace(/\s+/g, " ").trim(), fill, rule, g, bb });
}

const compact = parts.map((p) => ({ d: p.d, f: p.fill, r: p.rule === "evenodd" ? 1 : 0, g: p.mark }));
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
function boxOf(arr) {
  let x = Infinity, y = Infinity, x2 = -Infinity, y2 = -Infinity;
  arr.forEach((p) => {
    x = Math.min(x, p.bb[0]); y = Math.min(y, p.bb[1]);
    x2 = Math.max(x2, p.bb[0] + p.bb[2]); y2 = Math.max(y2, p.bb[1] + p.bb[3]);
  });
  return arr.length ? [x, y, x2 - x, y2 - y].map((v) => Math.round(v * 100) / 100) : [0, 0, 1, 1];
}
const gbox = {};
["mark", "furn", "word", "tag"].forEach((g) => (gbox[g] = boxOf(parts.filter((p) => p.g === g))));
const lines = parts
  .map((p) => `  { d: \`${esc(p.d)}\`, f: "${p.fill}", r: ${p.rule === "evenodd" ? 1 : 0}, g: "${p.g}", b: [${p.bb.map((v) => Math.round(v * 100) / 100).join(", ")}] },`)
  .join("\n");
const out = `/* GENERATED by tools/logo.mjs — do not edit by hand.
   Source: ${path.basename(SRC)} · ${parts.length} paths · viewBox ${vb.join(" ")}
   ------------------------------------------------------------------
   The Timberlane lockup as canvas path data, tagged by part so the reel can
   animate the emblem, the letters and the tagline independently.
   TLM.LOGOS.timberlane.svg(tint) rebuilds a tinted SVG string on demand, so a
   single copy of the geometry serves both the vector-path layers and the
   image layers (useful for a photo-background version of the mark). */
(function (global) {
  "use strict";
  var TLM = (global.TLM = global.TLM || {});
  var LOGOS = (TLM.LOGOS = TLM.LOGOS || {});
  var PARTS = [
${lines}
  ];
  /* left→right, so a per-part stagger reveals the wordmark letter by letter */
  function byX(a) {
    return a.slice().sort(function (p, q) {
      return p.b[0] - q.b[0] || p.b[1] - q.b[1];
    });
  }
  var L = {
    name: "timberlane",
    viewBox: [${vb.join(", ")}],
    parts: PARTS,
    groups: {
      mark: byX(PARTS.filter(function (p) { return p.g === "mark"; })),
      furn: byX(PARTS.filter(function (p) { return p.g === "furn"; })),
      word: byX(PARTS.filter(function (p) { return p.g === "word"; })),
      tag: byX(PARTS.filter(function (p) { return p.g === "tag"; })),
      all: byX(PARTS),
    },
    boxes: {
${["mark", "furn", "word", "tag", "all"].map((g) => `      ${g}: [${(g === "all" ? boxOf(parts) : gbox[g]).join(", ")}],`).join("\n")}    },
    box: function (g) { return this.boxes[g] || this.boxes.all; },
    svg: function (tint, bg) {
      var w = ${vb[2]}, h = ${vb[3]};
      var s = '<svg xmlns="http://www.w3.org/2000/svg" width="' + w + '" height="' + h + '" viewBox="' + "${vb.join(" ")}" + '">';
      if (bg) s += '<rect width="' + w + '" height="' + h + '" fill="' + bg + '"/>';
      for (var i = 0; i < PARTS.length; i++) {
        var p = PARTS[i];
        s += '<path d="' + p.d + '" fill="' + (tint || p.f) + '"' + (p.r ? ' fill-rule="evenodd"' : "") + "/>";
      }
      return s + "</svg>";
    },
  };
  LOGOS.timberlane = L;
})(typeof window !== "undefined" ? window : typeof globalThis !== "undefined" ? globalThis : this);
`;
fs.writeFileSync(OUT, out);
const by = (g) => parts.filter((p) => p.g === g).length;
console.log(`logo.js · ${parts.length} paths (mark ${by("mark")} · word ${by("word")} · tag ${by("tag")}) · ${(out.length / 1024).toFixed(1)} KB`);
console.log("bboxes:", parts.map((p) => `${p.g}${p.bb.join(",")}`).slice(0, 16).join("  "));
